### ISSUE TITLE
Project 2/3 Gruppenspeziefisches Bild

### ISSUE THREAD

**Issue by henrikgh** [henrikgh/Bildverarbeitung#1]
Im Projetktordner existieren noch weitere Bilder, die wir bearbeiten muessen.
Diese haben allerdings als besonderheit, das sie ueber einen schwarzen Balken oder Rahmen verfuegen.
Dies verfaelscht natuerlich das Endergebniss.
Wir sollten da noch irgenteine Routine einbauen, die solche Raender entfernt.

**Comment by henrikgh** [comment]
Ich habe euch ein neues Repository aufgemacht, in der wir Gruppenbetreffende Dinge wie z.B. Praesentationen hochladen koennen.
Packt das ganze aber bitte schoen getrennt in Unterordner, sons wird das schnell unuebersichtlich.

**Comment by henrikgh** [comment]
Muessen wir da ueberhaupt was dran aendern?
Hab mir das eben noch einmal durchgelesen und da steht nur, welche Erkenntniss kann man daraus ziehen kann. Fuer mich liess sich nicht so, alls das wir solche Flaechen erkennen und ausblenden sollen.
Guckt bitte nochmal drueber und sagt, was ihr dazu denkt.

**Comment by Buechta** [comment]
Ich verstehe das auch so, dass wir die Balken und Raender nicht entfernen sollen.

Wir sollten jedoch unseren Algorithmus und die verwendeten Gleichungen mit denen aus dem Burger-Burge-Buch vergleichen. In der 3. Auflage sind die Projektaufgaben 2/3 in den Kapiteln 4.3 und 4.4 beschrieben.
